package com.example.aidiagramgenerator.service;

import com.example.aidiagramgenerator.dto.request.DiagramRequest;
import com.example.aidiagramgenerator.dto.response.OpenAiDiagramResponse;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.util.Collections;
import java.util.List;

@Service
public class RuleBasedDiagramService {

    private static final Logger log = LoggerFactory.getLogger(RuleBasedDiagramService.class);

    public OpenAiDiagramResponse generate(DiagramRequest request) {
        String intent = request.getDetectedIntent();
        log.info("Generating diagram using rule-based fallback for intent: {}", intent);

        String diagramType = resolveType(intent);
        String plantUmlCode = buildPlantUml(request, diagramType);

        return OpenAiDiagramResponse.builder()
                .diagramType(diagramType)
                .plantUmlCode(plantUmlCode)
                .explanation("Generated by rule-based fallback system")
                .fallbackUsed(true)
                .modelUsed("RuleBased")
                .build();
    }

    private String resolveType(String intent) {
        if (intent == null || intent.isBlank()) return "sequence";
        String lower = intent.toLowerCase();
        if (lower.contains("object diagram") || lower.contains("instance") || lower.contains("instantiate")) return "object";
        if (lower.contains("class")) return "class";
        if (lower.contains("microservice") || lower.contains("api gateway") || lower.contains("service mesh")) return "microservices";
        if (lower.contains("component") || lower.contains("architecture")) return "component";
        if (lower.contains("usecase") || lower.contains("use case") || lower.contains("actor")) return "usecase";
        if (lower.contains("activity") || lower.contains("workflow") || lower.contains("process")
                || lower.contains("pipeline") || lower.contains("procedure")) return "activity";
        if (lower.contains("state") || lower.contains("transition") || lower.contains("lifecycle")
                || lower.contains("statechart")) return "state";
        return "sequence";
    }

    private String buildPlantUml(DiagramRequest request, String diagramType) {
        List<String> entities = request.getEntities() != null
                ? request.getEntities() : Collections.emptyList();
        List<String> relationships = request.getRelationships() != null
                ? request.getRelationships() : Collections.emptyList();

        StringBuilder sb = new StringBuilder("@startuml\n");
        switch (diagramType) {
            case "class"     -> buildClassDiagram(sb, entities, relationships);
            case "component" -> buildComponentDiagram(sb, entities, relationships);
            case "usecase"   -> buildUsecaseDiagram(sb, entities, relationships);
            case "object"        -> buildObjectDiagram(sb, entities, relationships);
            case "microservices" -> buildMicroservicesDiagram(sb, entities, relationships);
            case "activity"      -> buildActivityDiagram(sb, entities);
            case "state"         -> buildStateDiagram(sb, entities, relationships);
            default              -> buildSequenceDiagram(sb, entities, relationships);
        }
        sb.append("@enduml");
        return sb.toString();
    }

    private void buildSequenceDiagram(StringBuilder sb,
                                      List<String> entities,
                                      List<String> relationships) {
        entities.forEach(e -> sb.append("participant ").append(sanitize(e)).append("\n"));
        if (relationships.isEmpty() && entities.size() >= 2) {
            sb.append(sanitize(entities.get(0)))
              .append(" -> ")
              .append(sanitize(entities.get(1)))
              .append(" : call\n");
        } else {
            relationships.forEach(r -> sb.append("' ").append(r).append("\n"));
        }
    }

    private void buildClassDiagram(StringBuilder sb,
                                   List<String> entities,
                                   List<String> relationships) {
        entities.forEach(e -> sb.append("class ").append(sanitize(e)).append(" {}\n"));
        relationships.forEach(r -> sb.append("' ").append(r).append("\n"));
    }

    private void buildComponentDiagram(StringBuilder sb,
                                       List<String> entities,
                                       List<String> relationships) {
        entities.forEach(e -> sb.append("[").append(sanitize(e)).append("]\n"));
        relationships.forEach(r -> sb.append("' ").append(r).append("\n"));
    }

    private void buildUsecaseDiagram(StringBuilder sb,
                                     List<String> entities,
                                     List<String> relationships) {
        entities.forEach(e -> sb.append("usecase ").append(sanitize(e)).append("\n"));
        relationships.forEach(r -> sb.append("' ").append(r).append("\n"));
    }

    private void buildMicroservicesDiagram(StringBuilder sb, List<String> entities, List<String> relationships) {
        if (entities.isEmpty()) {
            sb.append("rectangle \"[API Gateway]\" as APIGateway\n");
            sb.append("rectangle \"[Auth Service]\" as AuthService\n");
            sb.append("rectangle \"[Order Service]\" as OrderService\n");
            sb.append("\n");
            sb.append("APIGateway --> AuthService : authenticate\n");
            sb.append("APIGateway --> OrderService : route\n");
        } else {
            entities.forEach(e -> sb.append("rectangle \"[").append(sanitize(e)).append("]\" as ")
                    .append(sanitize(e).replaceAll(" ", "_")).append("\n"));
            sb.append("\n");
            if (relationships.isEmpty()) {
                for (int i = 1; i < entities.size(); i++) {
                    sb.append(sanitize(entities.get(0)).replaceAll(" ", "_")).append(" --> ")
                      .append(sanitize(entities.get(i)).replaceAll(" ", "_")).append(" : route\n");
                }
            } else {
                relationships.forEach(r -> sb.append(r.replace("->", "-->")).append("\n"));
            }
        }
    }

    private void buildObjectDiagram(StringBuilder sb, List<String> entities, List<String> relationships) {
        if (entities.isEmpty()) {
            sb.append("object User1\n");
            sb.append("object Order1\n");
            sb.append("\n");
            sb.append("User1 --> Order1\n");
        } else {
            entities.forEach(e -> sb.append("object ").append(sanitize(e)).append("1\n"));
            sb.append("\n");
            if (relationships.isEmpty()) {
                for (int i = 0; i < entities.size() - 1; i++) {
                    sb.append(sanitize(entities.get(i))).append("1 --> ")
                      .append(sanitize(entities.get(i + 1))).append("1\n");
                }
            } else {
                relationships.forEach(r -> sb.append(r.replace("->", "-->")).append("\n"));
            }
        }
    }

    private void buildStateDiagram(StringBuilder sb, List<String> entities, List<String> relationships) {
        if (entities.isEmpty()) {
            sb.append("[*] --> Idle\n");
            sb.append("Idle --> Processing : start\n");
            sb.append("Processing --> Completed : finish\n");
            sb.append("Completed --> [*]\n");
        } else {
            sb.append("[*] --> ").append(sanitize(entities.get(0))).append("\n");
            for (int i = 0; i < entities.size() - 1; i++) {
                String label = (i < relationships.size()) ? sanitize(relationships.get(i)) : "transition";
                sb.append(sanitize(entities.get(i)))
                  .append(" --> ").append(sanitize(entities.get(i + 1)))
                  .append(" : ").append(label).append("\n");
            }
            sb.append(sanitize(entities.get(entities.size() - 1))).append(" --> [*]\n");
        }
    }

    private void buildActivityDiagram(StringBuilder sb, List<String> entities) {
        sb.append("start\n");
        if (entities.isEmpty()) {
            sb.append(":Initialize;\n");
            sb.append("--> :Process request;\n");
            sb.append("--> :Validate input;\n");
            sb.append("--> :Execute operation;\n");
            sb.append("--> :Return result;\n");
        } else {
            sb.append(":").append(sanitize(entities.get(0))).append(";\n");
            for (int i = 1; i < entities.size(); i++) {
                sb.append("--> :").append(sanitize(entities.get(i))).append(";\n");
            }
        }
        sb.append("stop\n");
    }

    private String sanitize(String name) {
        if (name == null) return "Unknown";
        return name.replaceAll("[^a-zA-Z0-9_ ]", "_");
    }
}
