CREATE TABLE IF NOT EXISTS diagrams (
    id UUID NOT NULL,
    input_type VARCHAR(255) NOT NULL,
    input_content TEXT NOT NULL,
    diagram_type VARCHAR(255) NOT NULL,
    mermaid_code TEXT NOT NULL,
    explanation TEXT,
    version_number INTEGER NOT NULL,
    parent_diagram_id UUID,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_diagrams PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS diagram_history (
    id VARCHAR(255) NOT NULL,
    diagram_type VARCHAR(255) NOT NULL,
    input_type VARCHAR(255) NOT NULL,
    input_content TEXT,
    mermaid_code TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_diagram_history PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS diagram_evaluations (
    id UUID NOT NULL,
    diagram_id UUID NOT NULL,
    clarity_score INTEGER NOT NULL,
    correctness_score INTEGER NOT NULL,
    usefulness_score INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_diagram_evaluations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS domain_diagrams (
    id UUID NOT NULL,
    input_text TEXT NOT NULL,
    diagram_type VARCHAR(255) NOT NULL,
    plant_uml_code TEXT NOT NULL,
    model_used VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_domain_diagrams PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS domain_diagram_evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    diagram_id UUID NOT NULL,
    clarity_score INTEGER NOT NULL,
    correctness_score INTEGER NOT NULL,
    usefulness_score INTEGER NOT NULL,
    comment TEXT,
    evaluated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_domain_diagram_evaluations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS style_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    diagram_type VARCHAR(255) NOT NULL,
    layout_direction VARCHAR(50),
    arrow_style VARCHAR(50),
    spacing_rule VARCHAR(100),
    CONSTRAINT pk_style_profiles PRIMARY KEY (id),
    CONSTRAINT uk_style_profiles_diagram_type_layout_direction UNIQUE (diagram_type, layout_direction)
);
